[package]
authors = ["Matthias Seitz <matthias.seitz@tum.de>"]
name = "archiveis"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["archive"]
description = """
Archive websites online
"""

[dependencies]
hyper = "0.12.7"
futures = "0.1.21"
clap = { version = "2.32.0", optional = true }
url = "1.7.1"
chrono = "0.4.5"

[badges]
travis-ci = { repository = "mattsse/archiveis-rs" }
