[package]
authors = ["Matthias Seitz <matthias.seitz@tum.de>"]
name = "elephant"
version = "0.1.0"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["archive"]
description = """
Archive websites online
"""

[dependencies]
hyper = "0.12.7"
futures = "0.1.21"

[badges]
travis-ci = { repository = "mattsse/elephant" }
